#!/bin/bash

clang -g -c -o core.a core.c &&
clang ~/boehm/lib/libgc.a core.a -g -o toccata toccata.c &&

./toccata hello.toc > hello.c &&
clang ~/boehm/lib/libgc.a core.a -g -o hello hello.c &&
./hello Universe
