#!/bin/bash

clang -fno-objc-arc -g -c -o core.a core.c &&
clang core.a -fno-objc-arc -g -o toccata toccata.c &&
./toccata examples/hello.toc > hello.c &&
clang core.a -fno-objc-arc -g -o hello hello.c &&
./hello Universe
